'use strict';
const assert=require('node:assert/strict'),path=require('node:path'),os=require('node:os');
const {chromium}=require('/private/tmp/claude-501/pw/node_modules/playwright');
const executablePath=path.join(os.homedir(),'Library/Caches/ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-mac-arm64/chrome-headless-shell');
(async()=>{const browser=await chromium.launch({executablePath}),page=await browser.newPage({viewport:{width:1280,height:720}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
const start=async()=>{await page.goto('file://'+path.resolve('index.html')+'#xiangyang');await page.waitForFunction(()=>mode==='scene')};
const closeSpeech=async()=>{await page.waitForSelector('#dlg:not([hidden]):not(.choose)');await page.locator('#dlg .txt').click();await page.locator('#dlg .txt').click()};
const open=async(id)=>{await page.evaluate(id=>{const n=cur.npcs.find(n=>n.id===id);player.x=n.x*TS;player.y=(n.y+1)*TS;cam.x=player.x-480/ZOOM;cam.y=player.y-270/ZOOM;window.testInteract=interact(n)},id);await page.waitForSelector('#npc-art-panel')};
try{await start();assert.deepEqual(await page.evaluate(()=>Object.values(S.npcArts)),[1,1,1,1,1]);
 await page.locator('#npc-arts-button').click();await page.waitForSelector('#npc-art-panel');assert.match(await page.locator('#npc-art-panel').innerText(),/临时授予/);await page.screenshot({path:'/tmp/npc-life-book.png'});await page.keyboard.press('Escape');await page.waitForFunction(()=>!busy&&!dlgBusy);
 await open('gossip');await page.screenshot({path:'/tmp/npc-life-actions.png'});await page.getByRole('button',{name:/^指导练习 · 打探/}).click();await page.waitForSelector('#dlg .choices button');await page.locator('#dlg .choices button').nth(2).click();await page.waitForSelector('#npc-art-panel');assert.equal(await page.evaluate(()=>S.npcArtProgress.inquire||0),0);
 for(let i=0;i<6;i++){await page.getByRole('button',{name:/^指导练习 · 打探/}).click();await page.waitForSelector('#dlg .choices button');const correct=await page.evaluate(()=>NPCArts.lesson('inquire').q[2]);await page.locator('#dlg .choices button').nth(correct).click();await closeSpeech();await page.waitForSelector('#npc-art-panel')}
 assert.equal(await page.evaluate(()=>S.npcArtProgress.inquire),6);assert.equal(await page.evaluate(()=>S.npcArts.inquire),1);assert.equal(await page.getByRole('button',{name:/^指导练习 · 打探/}).isDisabled(),true);assert.equal(await page.getByRole('button',{name:/^晋级考核 · 打探/}).isDisabled(),true);
 await page.getByRole('button',{name:/^打探 · 入门/}).click();await closeSpeech();await page.waitForSelector('#npc-art-panel');await page.getByRole('button',{name:/^晋级考核 · 打探/}).click();await page.waitForSelector('#dlg .choices button');const answer=await page.evaluate(()=>NPCArts.lesson('inquire',true).q[2]);await page.locator('#dlg .choices button').nth(answer).click();await closeSpeech();await page.waitForSelector('#npc-art-panel');assert.equal(await page.evaluate(()=>S.npcArts.inquire),2);
 await page.keyboard.press('Escape');await page.waitForFunction(()=>!busy&&!dlgBusy);const x=await page.evaluate(()=>player.x);await page.keyboard.down('d');await page.waitForTimeout(400);await page.keyboard.up('d');assert.ok(await page.evaluate(x=>player.x>x,x));
 // 真正切磋，不替换战斗；开启已实现的测试自动战斗。
 await page.evaluate(()=>{S.hp=derived().mhp;S.mp=derived().mmp;window.beforeSpar={hp:S.hp,mp:S.mp,exp:S.exp,silver:S.silver,bag:JSON.stringify(S.bag),flags:JSON.stringify(S.flags)}});await open('smith');await page.getByRole('button',{name:/^切磋 ·/}).click();await page.waitForSelector('#dlg .choices button');await page.locator('#dlg .choices button').first().click();await page.waitForFunction(()=>mode==='battle'&&B);assert.equal(await page.evaluate(()=>B.allies.length),1);assert.equal(await page.evaluate(()=>B.foes[0].exp),0);
 await page.waitForFunction(()=>B?.round>=1);await page.locator('#bt-auto').click();await page.waitForSelector('#bt-win',{timeout:90000});await page.screenshot({path:'/tmp/npc-life-spar.png'});await page.locator('#bt-win').click();await closeSpeech();await page.waitForSelector('#npc-art-panel');await page.keyboard.press('Escape');await page.waitForFunction(()=>!busy&&!dlgBusy&&mode==='scene');
 assert.deepEqual(await page.evaluate(()=>({hp:S.hp,mp:S.mp,exp:S.exp,silver:S.silver,bag:JSON.stringify(S.bag),flags:JSON.stringify(S.flags)})),await page.evaluate(()=>beforeSpar));assert.equal(await page.evaluate(()=>NPCArts.pending),false);
 assert.deepEqual(errors,[]);console.log('NPC arts browser PASS: Xiangyang grants/book, real NPC UI, training cancellation/cap/exam, movement, actual solo spar/zero rewards/resource restore');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
