"""Pack reviewed high-resolution menu icons without pixelation.

Run from repo root: python3 tools_scene/build_menu_icons_v2.py
Requires all originals in raw_menu_icons/; refuses partial replacement.
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
from PIL import Image
from scipy import ndimage

from build_menu_icons import ITEMS, SKILLS, XINFA

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / 'raw_menu_icons'
OUT = ROOT / 'assets/i_jianghu.webp'
META = ROOT / 'js/menu-icons.js'
COLS, CELL, PAD = 8, 192, 17


def remove_white_background(im: Image.Image) -> Image.Image:
    if im.mode == 'RGBA' and im.getchannel('A').getextrema()[0] < 250:
        return im
    rgb = np.asarray(im.convert('RGB')).astype(np.float32)
    light = rgb.min(axis=2) >= 238
    labels, _ = ndimage.label(light)
    edge_ids = np.unique(np.concatenate((labels[0], labels[-1], labels[:, 0], labels[:, -1])))
    bg = np.isin(labels, edge_ids[edge_ids > 0])
    bg = ndimage.binary_closing(bg, iterations=1) | bg
    alpha = np.where(bg, 0.0, 1.0)
    band = ndimage.binary_dilation(bg, iterations=3) & ~bg
    alpha[band] = np.clip((235 - rgb.min(axis=2)[band]) / 65, 0, 1)
    safe = np.maximum(alpha, 0.01)[..., None]
    color = np.where(band[..., None], (rgb - 255 * (1 - safe)) / safe, rgb)
    rgba = np.dstack((np.clip(color, 0, 255), alpha * 255)).astype(np.uint8)
    return Image.fromarray(rgba)


def fitted_icon(path: Path) -> Image.Image:
    im = remove_white_background(Image.open(path).convert('RGBA'))
    box = im.getchannel('A').getbbox()
    if not box:
        raise ValueError(f'Empty icon: {path}')
    im = im.crop(box)
    im.thumbnail((CELL - PAD * 2, CELL - PAD * 2), Image.Resampling.LANCZOS)
    return im


def main() -> None:
    groups = {'item': ITEMS, 'skill': SKILLS, 'xinfa': XINFA}
    entries = [(kind, key) for kind, group in groups.items() for key in group]
    missing = [f'{kind}/{key}' for kind, key in entries if not (RAW / f'{kind}_{key}.png').exists()]
    if missing:
        raise SystemExit('Refusing partial atlas; missing ' + ', '.join(missing))
    rows = (len(entries) + COLS - 1) // COLS
    atlas = Image.new('RGBA', (COLS * CELL, rows * CELL))
    meta = {'cols': COLS, 'rows': rows, 'cell': CELL, 'item': {}, 'skill': {}, 'xinfa': {}}
    for i, (kind, key) in enumerate(entries):
        icon = fitted_icon(RAW / f'{kind}_{key}.png')
        x, y = (i % COLS) * CELL, (i // COLS) * CELL
        atlas.alpha_composite(icon, (x + (CELL - icon.width) // 2, y + (CELL - icon.height) // 2))
        meta[kind][key] = [i % COLS, i // COLS]
    pixels = np.asarray(atlas).copy()
    pixels[pixels[:, :, 3] == 0, :3] = 0
    atlas = Image.fromarray(pixels)
    atlas.save(OUT, lossless=True, method=6)
    META.write_text("'use strict';\n// Generated by tools_scene/build_menu_icons_v2.py from individually reviewed originals.\nwindow.MENU_ICONS = "
                    + json.dumps(meta, ensure_ascii=False, separators=(',', ':')) + ';\n', encoding='utf-8')
    print(f'{len(entries)} non-pixel icons -> {OUT.relative_to(ROOT)} {atlas.size}; {META.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
